/*random strings*/
var textArray = [
    'function makeid(length) { \n',
    'result = keychain \n',
    'for(true){alizard=cool}\n',
    'charactersLength = characters.length;\n',
    'false = true;\n',
    'document.addEventListener("keydown",function(event) {\n',
    '}\n',
    'event.preventDefault();\n',
    'gorillaFirst();\n',
    'struct group_info init_groups = { .usage = ATOMIC_INIT(3) };\n',
    '	struct group_info *group_info;\n',
    '   gaming = true;\n',
    'Camelcasing();\n',
    'Function DesktobMode{DesktobMode()}\n',
    'ebounce(42);\n',
    '//backluck\n',
    'e = f;\n',
    'f = g;\n',
    'clicker();\n',
    'subtoalizardguy;\n',
    '//lol\n',
    'trapped + sphere = panic;\n',
    'robotry:bobotby;\n',
    'presets(-1);\n',
    'help = url("https://rep-tiled.tk/mainframe/help");\n',
    'reset(favicon);\n'
];